### ISSUE TITLE
Create abstraction Layer for weightsave

### ISSUE THREAD

**Issue by EricMiddelhove** [Vubito32/Simple-AI#10]
Would be great if you could implement a method wich saves / overwrites the saved weights and a method wich returns the weigths

**Comment by vntxx** [comment]
Probably requires #4 (and #8) first

(#8 initially requested this too)

**Comment by EricMiddelhove** [comment]
to solve this create branch from inheritace-structure branch

**Comment by vntxx** [comment]
This was done (?)
