### ISSUE TITLE
Saving Weights in an abstract implementation of the Network / Perceptron

### ISSUE THREAD

**Issue by vntxx** [Vubito32/Simple-AI#8]
# Saving Weights in an abstract implementation of the Network / Perceptron
## Motivation
Every network such as the primary color detector would derive from an abstract network class which provides methods for storing perceptrons in a datastructure and saving weights of those available thus allowing easier storage / saving of states (weights)
A network should get a save/load state method and every perceptron should get a save/load weights method each defined in the superclass

Would potentially make #7 more stable hence closing #1 entirely

### If you like the idea just assign me and i'll work on a first basic iteration of this

**Comment by EricMiddelhove** [comment]
I think we should create something like a class diagram so everybody knows what they are talking about. We can also put issue #4 together with this one

**Comment by EricMiddelhove** [comment]
Doubled with #4

**Comment by vntxx** [comment]
Not quite, because of the saving of the structure. Please reopen this issue as saving isn't implemented in a superclass yet

**Comment by EricMiddelhove** [comment]
there wont be another Network super class. This project is not meant to contain more than one network

**Comment by vntxx** [comment]
I would actually like to provide a superclass for the perceptron aswell as the network
A superclass for a network might be out of scope for this project but it would allow an implementation of such behaviour that is quite more modular so i would recommend to reconsider this

**Comment by EricMiddelhove** [comment]
#4

**Comment by vntxx** [comment]
#10 would be doubled then, becaue this implies its goal

**Comment by EricMiddelhove** [comment]
then close it and do this :D

**Comment by EricMiddelhove** [comment]
also fix runtime issue with _loadWeights(File, String, Perceptron)
